base_link = ""
admin = base_link + "/admin"
authorization = base_link + "/authorization"
registration = base_link + "/registration"
calendar = base_link + "/calendar"
main_page = base_link + "/"
day_plan = base_link + "/day_plan"
selected_products = base_link + "/selected_products"
answers = base_link + '/answers'
about = base_link + '/about'
cabinet = base_link + '/cabinet'
all_news =  base_link + '/all_news'
one_news =  base_link + '/one_news/<int:news_id>'
process_registration = base_link + '/process_registration'
confirm_code = base_link + '/confirm_code'
process_login = base_link + '/process_login',
logout = base_link + '/logout'

header_links = ["/", day_plan, calendar, cabinet, all_news, authorization, registration, ]
